name: Scheduled Build
on:
  schedule:
    - cron: '43 20 * * *' # Runs every day at 20:43 UTC
  workflow_dispatch:   # Allows you to run it manually

jobs:
  build:
    runs-box: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pages/builds
